// @generated: @expo/next-adapter@2.1.9
import "./_app.css";
import React from "react";
import { tw, Text, View } from "tw-rn";
import { ScrollView } from "react-native";

const layoutStyles = [
  "hidden",
  "block",
  "flow-root",
  "inline-block",
  "inline",
  "flex",
  "inline-flex",
  "grid",
  "inline-grid",
  "table",
  "table-caption",
  "table-cell",
  "table-column",
  "table-column-group",
  "table-footer-group",
  "table-header-group",
  "table-row-group",
  "table-row",
  "overflow-hidden",
  "overflow-visible",
  "overflow-scroll",
  "static",
  "fixed",
  "absolute",
  "relative",
  "sticky",
  "inset-0",
  "inset-y-0",
  "inset-x-0",
  "top-0",
  "right-0",
  "bottom-0",
  "left-0",
  "inset-auto",
  "visible",
  "invisible",
  "z-0",
  "z-10",
  "z-20",
  "z-30",
  "z-40",
  "z-50",
  "flex-row",
  "flex-row-reverse",
  "flex-col",
  "flex-col-reverse",
  "flex-no-wrap",
  "flex-wrap",
  "flex-wrap-reverse",
  "items-stretch",
  "items-start",
  "items-center",
  "items-end",
  "items-baseline",
  "content-start",
  "content-center",
  "content-end",
  "content-between",
  "content-around",
  "self-auto",
  "self-start",
  "self-center",
  "self-end",
  "self-stretch",
  "justify-start",
  "justify-center",
  "justify-end",
  "justify-between",
  "justify-around",
  "flex-grow",
  "flex-grow-0",
  "flex-shrink",
  "flex-shrink-0",
  "p-0",
  "p-px",
  "py-0",
  "py-px",
  "px-0",
  "px-px",
  "pt-0",
  "pt-px",
  "pr-0",
  "pr-1",
  "pr-2",
  "pr-3",
  "pr-4",
  "pr-5",
  "pr-6",
  "pr-8",
  "pr-10",
  "pr-12",
  "pr-16",
  "pr-20",
  "pr-24",
  "pr-32",
  "pr-40",
  "pr-48",
  "pr-56",
  "pr-64",
  "pr-px",
  "pb-0",
  "pb-1",
  "pb-2",
  "pb-3",
  "pb-4",
  "pb-5",
  "pb-6",
  "pb-8",
  "pb-10",
  "pb-12",
  "pb-16",
  "pb-20",
  "pb-24",
  "pb-32",
  "pb-40",
  "pb-48",
  "pb-56",
  "pb-64",
  "pb-px",
  "pl-0",
  "pl-1",
  "pl-2",
  "pl-3",
  "pl-4",
  "pl-5",
  "pl-6",
  "pl-8",
  "pl-10",
  "pl-12",
  "pl-16",
  "pl-20",
  "pl-24",
  "pl-32",
  "pl-40",
  "pl-48",
  "pl-56",
  "pl-64",
  "pl-px",
  "m-0",
  "m-1",
  "m-2",
  "m-3",
  "m-4",
  "m-5",
  "m-6",
  "m-8",
  "m-10",
  "m-12",
  "m-16",
  "m-20",
  "m-24",
  "m-32",
  "m-40",
  "m-48",
  "m-56",
  "m-64",
  "m-auto",
  "m-px",
  "-m-1",
  "-m-2",
  "-m-3",
  "-m-4",
  "-m-5",
  "-m-6",
  "-m-8",
  "-m-10",
  "-m-12",
  "-m-16",
  "-m-20",
  "-m-24",
  "-m-32",
  "-m-40",
  "-m-48",
  "-m-56",
  "-m-64",
  "-m-px",
  "my-0",
  "my-1",
  "my-2",
  "my-3",
  "my-4",
  "my-5",
  "my-6",
  "my-8",
  "my-10",
  "my-12",
  "my-16",
  "my-20",
  "my-24",
  "my-32",
  "my-40",
  "my-48",
  "my-56",
  "my-64",
  "my-auto",
  "my-px",
  "-my-1",
  "-my-2",
  "-my-3",
  "-my-4",
  "-my-5",
  "-my-6",
  "-my-8",
  "-my-10",
  "-my-12",
  "-my-16",
  "-my-20",
  "-my-24",
  "-my-32",
  "-my-40",
  "-my-48",
  "-my-56",
  "-my-64",
  "-my-px",
  "mx-0",
  "mx-1",
  "mx-2",
  "mx-3",
  "mx-4",
  "mx-5",
  "mx-6",
  "mx-8",
  "mx-10",
  "mx-12",
  "mx-16",
  "mx-20",
  "mx-24",
  "mx-32",
  "mx-40",
  "mx-48",
  "mx-56",
  "mx-64",
  "mx-auto",
  "mx-px",
  "-mx-1",
  "-mx-2",
  "-mx-3",
  "-mx-4",
  "-mx-5",
  "-mx-6",
  "-mx-8",
  "-mx-10",
  "-mx-12",
  "-mx-16",
  "-mx-20",
  "-mx-24",
  "-mx-32",
  "-mx-40",
  "-mx-48",
  "-mx-56",
  "-mx-64",
  "-mx-px",
  "mt-0",
  "mt-1",
  "mt-2",
  "mt-3",
  "mt-4",
  "mt-5",
  "mt-6",
  "mt-8",
  "mt-10",
  "mt-12",
  "mt-16",
  "mt-20",
  "mt-24",
  "mt-32",
  "mt-40",
  "mt-48",
  "mt-56",
  "mt-64",
  "mt-auto",
  "mt-px",
  "-mt-1",
  "-mt-2",
  "-mt-3",
  "-mt-4",
  "-mt-5",
  "-mt-6",
  "-mt-8",
  "-mt-10",
  "-mt-12",
  "-mt-16",
  "-mt-20",
  "-mt-24",
  "-mt-32",
  "-mt-40",
  "-mt-48",
  "-mt-56",
  "-mt-64",
  "-mt-px",
  "mr-0",
  "mr-1",
  "mr-2",
  "mr-3",
  "mr-4",
  "mr-5",
  "mr-6",
  "mr-8",
  "mr-10",
  "mr-12",
  "mr-16",
  "mr-20",
  "mr-24",
  "mr-32",
  "mr-40",
  "mr-48",
  "mr-56",
  "mr-64",
  "mr-auto",
  "mr-px",
  "-mr-1",
  "-mr-2",
  "-mr-3",
  "-mr-4",
  "-mr-5",
  "-mr-6",
  "-mr-8",
  "-mr-10",
  "-mr-12",
  "-mr-16",
  "-mr-20",
  "-mr-24",
  "-mr-32",
  "-mr-40",
  "-mr-48",
  "-mr-56",
  "-mr-64",
  "-mr-px",
  "mb-0",
  "mb-1",
  "mb-2",
  "mb-3",
  "mb-4",
  "mb-5",
  "mb-6",
  "mb-8",
  "mb-10",
  "mb-12",
  "mb-16",
  "mb-20",
  "mb-24",
  "mb-32",
  "mb-40",
  "mb-48",
  "mb-56",
  "mb-64",
  "mb-auto",
  "mb-px",
  "-mb-1",
  "-mb-2",
  "-mb-3",
  "-mb-4",
  "-mb-5",
  "-mb-6",
  "-mb-8",
  "-mb-10",
  "-mb-12",
  "-mb-16",
  "-mb-20",
  "-mb-24",
  "-mb-32",
  "-mb-40",
  "-mb-48",
  "-mb-56",
  "-mb-64",
  "-mb-px",
  "ml-0",
  "ml-1",
  "ml-2",
  "ml-3",
  "ml-4",
  "ml-5",
  "ml-6",
  "ml-8",
  "ml-10",
  "ml-12",
  "ml-16",
  "ml-20",
  "ml-24",
  "ml-32",
  "ml-40",
  "ml-48",
  "ml-56",
  "ml-64",
  "ml-auto",
  "ml-px",
  "-ml-1",
  "-ml-2",
  "-ml-3",
  "-ml-4",
  "-ml-5",
  "-ml-6",
  "-ml-8",
  "-ml-10",
  "-ml-12",
  "-ml-16",
  "-ml-20",
  "-ml-24",
  "-ml-32",
  "-ml-40",
  "-ml-48",
  "-ml-56",
  "-ml-64",
  "-ml-px",
  "w-0",
  "w-1",
  "w-2",
  "w-3",
  "w-4",
  "w-5",
  "w-6",
  "w-8",
  "w-10",
  "w-12",
  "w-16",
  "w-20",
  "w-24",
  "w-32",
  "w-40",
  "w-48",
  "w-56",
  "w-64",
  "w-px",
  "w-1/2",
  "w-1/3",
  "w-2/3",
  "w-1/4",
  "w-2/4",
  "w-3/4",
  "w-1/5",
  "w-2/5",
  "w-3/5",
  "w-4/5",
  "w-1/6",
  "w-2/6",
  "w-3/6",
  "w-4/6",
  "w-5/6",
  "w-1/12",
  "w-2/12",
  "w-3/12",
  "w-4/12",
  "w-5/12",
  "w-6/12",
  "w-7/12",
  "w-8/12",
  "w-9/12",
  "w-10/12",
  "w-11/12",
  "w-full",
  "min-w-0",
  "min-w-full",
  "max-w-xs",
  "max-w-sm",
  "max-w-md",
  "max-w-lg",
  "max-w-xl",
  "max-w-2xl",
  "max-w-3xl",
  "max-w-4xl",
  "max-w-5xl",
  "max-w-6xl",
  "max-w-full",
  "max-w-screen-sm",
  "max-w-screen-md",
  "max-w-screen-lg",
  "max-w-screen-xl",
  "h-0",
  "h-1",
  "h-2",
  "h-3",
  "h-4",
  "h-5",
  "h-6",
  "h-8",
  "h-10",
  "h-12",
  "h-16",
  "h-20",
  "h-24",
  "h-32",
  "h-40",
  "h-48",
  "h-56",
  "h-64",
  "h-px",
  "h-full",
  "min-h-0",
  "min-h-full",
  "max-h-full",
  "bg-transparent",
  "bg-black",
  "bg-white",
  "bg-gray-100",
  "bg-gray-200",
  "bg-gray-300",
  "bg-gray-400",
  "bg-gray-500",
  "bg-gray-600",
  "bg-gray-700",
  "bg-gray-800",
  "bg-gray-900",
  "bg-red-100",
  "bg-red-200",
  "bg-red-300",
  "bg-red-400",
  "bg-red-500",
  "bg-red-600",
  "bg-red-700",
  "bg-red-800",
  "bg-red-900",
  "bg-orange-100",
  "bg-orange-200",
  "bg-orange-300",
  "bg-orange-400",
  "bg-orange-500",
  "bg-orange-600",
  "bg-orange-700",
  "bg-orange-800",
  "bg-orange-900",
  "bg-yellow-100",
  "bg-yellow-200",
  "bg-yellow-300",
  "bg-yellow-400",
  "bg-yellow-500",
  "bg-yellow-600",
  "bg-yellow-700",
  "bg-yellow-800",
  "bg-yellow-900",
  "bg-green-100",
  "bg-green-200",
  "bg-green-300",
  "bg-green-400",
  "bg-green-500",
  "bg-green-600",
  "bg-green-700",
  "bg-green-800",
  "bg-green-900",
  "bg-teal-100",
  "bg-teal-200",
  "bg-teal-300",
  "bg-teal-400",
  "bg-teal-500",
  "bg-teal-600",
  "bg-teal-700",
  "bg-teal-800",
  "bg-teal-900",
  "bg-blue-100",
  "bg-blue-200",
  "bg-blue-300",
  "bg-blue-400",
  "bg-blue-500",
  "bg-blue-600",
  "bg-blue-700",
  "bg-blue-800",
  "bg-blue-900",
  "bg-indigo-100",
  "bg-indigo-200",
  "bg-indigo-300",
  "bg-indigo-400",
  "bg-indigo-500",
  "bg-indigo-600",
  "bg-indigo-700",
  "bg-indigo-800",
  "bg-indigo-900",
  "bg-purple-100",
  "bg-purple-200",
  "bg-purple-300",
  "bg-purple-400",
  "bg-purple-500",
  "bg-purple-600",
  "bg-purple-700",
  "bg-purple-800",
  "bg-purple-900",
  "bg-pink-100",
  "bg-pink-200",
  "bg-pink-300",
  "bg-pink-400",
  "bg-pink-500",
  "bg-pink-600",
  "bg-pink-700",
  "bg-pink-800",
  "bg-pink-900",
  "rounded-none",
  "rounded-sm",
  "rounded",
  "rounded-md",
  "rounded-lg",
  "rounded-full",
  "rounded-t-none",
  "rounded-r-none",
  "rounded-b-none",
  "rounded-l-none",
  "rounded-t-sm",
  "rounded-r-sm",
  "rounded-b-sm",
  "rounded-l-sm",
  "rounded-t",
  "rounded-r",
  "rounded-b",
  "rounded-l",
  "rounded-t-md",
  "rounded-r-md",
  "rounded-b-md",
  "rounded-l-md",
  "rounded-t-lg",
  "rounded-r-lg",
  "rounded-b-lg",
  "rounded-l-lg",
  "rounded-t-full",
  "rounded-r-full",
  "rounded-b-full",
  "rounded-l-full",
  "rounded-tl-none",
  "rounded-tr-none",
  "rounded-br-none",
  "rounded-bl-none",
  "rounded-tl-sm",
  "rounded-tr-sm",
  "rounded-br-sm",
  "rounded-bl-sm",
  "rounded-tl",
  "rounded-tr",
  "rounded-br",
  "rounded-bl",
  "rounded-tl-md",
  "rounded-tr-md",
  "rounded-br-md",
  "rounded-bl-md",
  "rounded-tl-lg",
  "rounded-tr-lg",
  "rounded-br-lg",
  "rounded-bl-lg",
  "rounded-tl-full",
  "rounded-tr-full",
  "rounded-br-full",
  "rounded-bl-full",
  "border",
  "border-0",
  "border-2",
  "border-4",
  "border-8",
  "border-t",
  "border-r",
  "border-b",
  "border-l",
  "border-t-0",
  "border-r-0",
  "border-b-0",
  "border-l-0",
  "border-t-2",
  "border-r-2",
  "border-b-2",
  "border-l-2",
  "border-t-4",
  "border-r-4",
  "border-b-4",
  "border-l-4",
  "border-t-8",
  "border-r-8",
  "border-b-8",
  "border-l-8",
  "border border-transparent",
  "border border-black",
  "border border-white",
  "border border-gray-100",
  "border border-gray-200",
  "border border-gray-300",
  "border border-gray-400",
  "border border-gray-500",
  "border border-gray-600",
  "border border-gray-700",
  "border border-gray-800",
  "border border-gray-900",
  "border border-red-100",
  "border border-red-200",
  "border border-red-300",
  "border border-red-400",
  "border border-red-500",
  "border border-red-600",
  "border border-red-700",
  "border border-red-800",
  "border border-red-900",
  "border border-orange-100",
  "border border-orange-200",
  "border border-orange-300",
  "border border-orange-400",
  "border border-orange-500",
  "border border-orange-600",
  "border border-orange-700",
  "border border-orange-800",
  "border border-orange-900",
  "border border-yellow-100",
  "border border-yellow-200",
  "border border-yellow-300",
  "border border-yellow-400",
  "border border-yellow-500",
  "border border-yellow-600",
  "border border-yellow-700",
  "border border-yellow-800",
  "border border-yellow-900",
  "border border-green-100",
  "border border-green-200",
  "border border-green-300",
  "border border-green-400",
  "border border-green-500",
  "border border-green-600",
  "border border-green-700",
  "border border-green-800",
  "border border-green-900",
  "border border-teal-100",
  "border border-teal-200",
  "border border-teal-300",
  "border border-teal-400",
  "border border-teal-500",
  "border border-teal-600",
  "border border-teal-700",
  "border border-teal-800",
  "border border-teal-900",
  "border border-blue-100",
  "border border-blue-200",
  "border border-blue-300",
  "border border-blue-400",
  "border border-blue-500",
  "border border-blue-600",
  "border border-blue-700",
  "border border-blue-800",
  "border border-blue-900",
  "border border-indigo-100",
  "border border-indigo-200",
  "border border-indigo-300",
  "border border-indigo-400",
  "border border-indigo-500",
  "border border-indigo-600",
  "border border-indigo-700",
  "border border-indigo-800",
  "border border-indigo-900",
  "border border-purple-100",
  "border border-purple-200",
  "border border-purple-300",
  "border border-purple-400",
  "border border-purple-500",
  "border border-purple-600",
  "border border-purple-700",
  "border border-purple-800",
  "border border-purple-900",
  "border border-pink-100",
  "border border-pink-200",
  "border border-pink-300",
  "border border-pink-400",
  "border border-pink-500",
  "border border-pink-600",
  "border border-pink-700",
  "border border-pink-800",
  "border border-pink-900",
  "border border-solid",
  "border border-dashed",
  "border border-dotted",
  "opacity-100",
  "opacity-75",
  "opacity-50",
  "opacity-25",
  "opacity-0",
  "cursor-auto",
  "cursor-default",
  "cursor-pointer",
  "cursor-wait",
  "cursor-text",
  "cursor-move",
  "cursor-not-allowed",
  "select-none",
  "select-text",
  "select-all",
  "select-auto",
];

const textStyles = [
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "text-3xl",
  "text-4xl",
  "text-5xl",
  "text-6xl",
  "italic",
  "not-italic",
  "font-hairline",
  "font-thin",
  "font-light",
  "font-normal",
  "font-medium",
  "font-semibold",
  "font-bold",
  "font-extrabold",
  "font-black",
  "tracking-tighter",
  "tracking-tight",
  "tracking-normal",
  "tracking-wide",
  "tracking-wider",
  "tracking-widest",
  "leading-3",
  "leading-4",
  "leading-5",
  "leading-6",
  "leading-7",
  "leading-8",
  "leading-9",
  "leading-10",
  "text-left",
  "text-center",
  "text-right",
  "text-transparent",
  "text-black",
  "text-white",
  "text-gray-100",
  "text-gray-200",
  "text-gray-300",
  "text-gray-400",
  "text-gray-500",
  "text-gray-600",
  "text-gray-700",
  "text-gray-800",
  "text-gray-900",
  "text-red-100",
  "text-red-200",
  "text-red-300",
  "text-red-400",
  "text-red-500",
  "text-red-600",
  "text-red-700",
  "text-red-800",
  "text-red-900",
  "text-orange-100",
  "text-orange-200",
  "text-orange-300",
  "text-orange-400",
  "text-orange-500",
  "text-orange-600",
  "text-orange-700",
  "text-orange-800",
  "text-orange-900",
  "text-yellow-100",
  "text-yellow-200",
  "text-yellow-300",
  "text-yellow-400",
  "text-yellow-500",
  "text-yellow-600",
  "text-yellow-700",
  "text-yellow-800",
  "text-yellow-900",
  "text-green-100",
  "text-green-200",
  "text-green-300",
  "text-green-400",
  "text-green-500",
  "text-green-600",
  "text-green-700",
  "text-green-800",
  "text-green-900",
  "text-teal-100",
  "text-teal-200",
  "text-teal-300",
  "text-teal-400",
  "text-teal-500",
  "text-teal-600",
  "text-teal-700",
  "text-teal-800",
  "text-teal-900",
  "text-blue-100",
  "text-blue-200",
  "text-blue-300",
  "text-blue-400",
  "text-blue-500",
  "text-blue-600",
  "text-blue-700",
  "text-blue-800",
  "text-blue-900",
  "text-indigo-100",
  "text-indigo-200",
  "text-indigo-300",
  "text-indigo-400",
  "text-indigo-500",
  "text-indigo-600",
  "text-indigo-700",
  "text-indigo-800",
  "text-indigo-900",
  "text-purple-100",
  "text-purple-200",
  "text-purple-300",
  "text-purple-400",
  "text-purple-500",
  "text-purple-600",
  "text-purple-700",
  "text-purple-800",
  "text-purple-900",
  "text-pink-100",
  "text-pink-200",
  "text-pink-300",
  "text-pink-400",
  "text-pink-500",
  "text-pink-600",
  "text-pink-700",
  "text-pink-800",
  "text-pink-900",
  "uppercase",
  "lowercase",
  "capitalize",
  "normal-case",
  "align-baseline",
];

export default function App() {
  return (
    <View style={tw`test items-center justify-center`}>
      <ScrollView>
        {/* layout Display Styles */}
        {layoutStyles.map((s) => {
          return (
            <View key={s} style={tw`${s}`}>
              <Text style={{ color: "gray" }}>{s}</Text>
            </View>
          );
        })}
        {textStyles.map((s) => {
          return (
            <View key={s}>
              <Text style={tw`${s}`}>{s}</Text>
            </View>
          );
        })}
      </ScrollView>
    </View>
  );
}
