module.exports = {
  "": {
    "bg-white": { backgroundColor: "#ffffff" },
    "bg-black": { backgroundColor: "#000000" },
    "h-100": { height: 100 },
    "w-100": { width: 100 },
    "p-1": { padding: 4 },
    "p-4": {
      paddingTop: 10,
      paddingRight: 10,
      paddingBottom: 10,
      paddingLeft: 10,
    },
    "transition-none": { transitionProperty: [] },
    "transition-all": { transitionProperty: ["all"] },
    transition: {
      transitionProperty: [
        "background-color",
        "border-color",
        "color",
        "fill",
        "stroke",
        "opacity",
        "box-shadow",
        "transform",
      ],
    },
    "transition-colors": {
      transitionProperty: [
        "background-color",
        "border-color",
        "color",
        "fill",
        "stroke",
      ],
    },
    "transition-opacity": { transitionProperty: ["opacity"] },
    "transition-shadow": { transitionProperty: ["box-shadow"] },
    "transition-transform": { transitionProperty: ["transform"] },
    "duration-75": { transitionDuration: 75 },
    "delay-75": { transitionDelay: 75 },
    "ease-in-out": {
      transitionTimingFunction: { type: "bezier", args: [0.4, 0, 0.2, 1] },
    },
  },
  "(min-width: 640px)": { "sm:bg-red": { backgroundColor: "#ff0000" } },
  "(min-width: 768px)": { "md:bg-green": { backgroundColor: "#00ff00" } },
  "(min-width: 1024px)": { "lg:bg-blue": { backgroundColor: "#0000ff" } },
  "(min-width: 1280px)": { "xl:bg-black": { backgroundColor: "#000000" } },
};
