module.exports = {
  sidebar: [
    {
      type: "category",
      label: "Fundamentals",
      collapsed: false,
      items: [
        "fundamentals/getting-started",
        "fundamentals/usage",
        "fundamentals/components",
        "fundamentals/tw",
        "fundamentals/withtwrn",
        "fundamentals/react-native-web-responsive",
        "fundamentals/pseudo-class-variants",
      ],
    },
    {
      type: "category",
      label: "Styles",
      collapsed: false,
      items: [
        {
          Layout: [
            "styles/layout/container",
            "styles/layout/box-sizing",
            "styles/layout/display",
            "styles/layout/float",
            "styles/layout/clear",
            "styles/layout/object-fit",
            "styles/layout/object-position",
            "styles/layout/overflow",
            "styles/layout/position",
            "styles/layout/top-right-bottom-left",
            "styles/layout/z-index",
          ],
          Flexbox: [
            "styles/flexbox/flex-direction",
            "styles/flexbox/flex-wrap",
            "styles/flexbox/align-items",
            "styles/flexbox/align-content",
            "styles/flexbox/align-self",
            "styles/flexbox/justify-content",
            "styles/flexbox/flex",
            "styles/flexbox/flex-grow",
            "styles/flexbox/flex-shrink",
            "styles/flexbox/order",
          ],
          Grid: [
            "styles/grid/grid-template-columns",
            "styles/grid/grid-columns",
            "styles/grid/grid-template-rows",
            "styles/grid/grid-rows",
            "styles/grid/gap",
            "styles/grid/grid-auto-flow",
          ],
          Spacing: [
            "styles/spacing/padding",
            "styles/spacing/margin",
            "styles/spacing/space-between",
          ],
          Sizing: [
            "styles/sizing/width",
            "styles/sizing/min-width",
            "styles/sizing/max-width",
            "styles/sizing/height",
            "styles/sizing/min-height",
            "styles/sizing/max-height",
          ],
          Typography: [
            "styles/typography/font-family",
            "styles/typography/font-size",
            "styles/typography/font-smoothing",
            "styles/typography/font-style",
            "styles/typography/font-weight",
            "styles/typography/letter-spacing",
            "styles/typography/line-height",
            "styles/typography/list-style-type",
            "styles/typography/placeholder-color",
            "styles/typography/placeholder-opacity",
            "styles/typography/text-align",
            "styles/typography/text-color",
            "styles/typography/text-opacity",
            "styles/typography/text-decoration",
            "styles/typography/text-transform",
            "styles/typography/vertical-alignment",
            "styles/typography/whitespace",
            "styles/typography/word-break",
          ],
          Backgrounds: [
            "styles/backgrounds/background-attachment",
            "styles/backgrounds/background-color",
            "styles/backgrounds/background-opacity",
            "styles/backgrounds/background-position",
            "styles/backgrounds/background-repeat",
            "styles/backgrounds/background-size",
          ],
          Borders: [
            "styles/borders/border-radius",
            "styles/borders/border-width",
            "styles/borders/border-color",
            "styles/borders/border-opacity",
            "styles/borders/border-style",
            "styles/borders/divide-width",
            "styles/borders/divide-color",
            "styles/borders/divide-opacity",
          ],
          Tables: [
            "styles/tables/border-collapse",
            "styles/tables/table-layout",
          ],
          Effects: ["styles/effects/box-shadow", "styles/effects/opacity"],
          Transitions: [
            "styles/transitions/transition-property",
            "styles/transitions/transition-duration",
            "styles/transitions/transition-timing-function",
            "styles/transitions/transition-delay",
          ],
          Transforms: [
            "styles/transforms/scale",
            "styles/transforms/rotate",
            "styles/transforms/translate",
            "styles/transforms/skew",
            "styles/transforms/transform-origin",
          ],
          Interactivity: [
            "styles/interactivity/appareance",
            "styles/interactivity/cursor",
            "styles/interactivity/outline",
            "styles/interactivity/pointer-events",
            "styles/interactivity/resize",
            "styles/interactivity/user-select",
          ],
          SVG: [
            "styles/svg/fill",
            "styles/svg/stroke",
            "styles/svg/stroke-width",
          ],
          Accessibility: ["styles/accessibility/screen-readers"],
        },
      ],
    },
  ],
};
